/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
class AppTest {
    // ---------- add ----------

    @Test void testAdd() {
        assertEquals(5, App.add(2, 3));
        assertEquals(-1, App.add(-2, 1));
    }

    @Test void testAddWithZero() {
        assertEquals(0, App.add(0, 0));
        assertEquals(7, App.add(7, 0));
        assertEquals(7, App.add(0, 7));
    }

    @Test void testAddNegatives() {
        assertEquals(-8, App.add(-3, -5));
        assertEquals(0, App.add(-4, 4));
    }

    @Test void testAddIsCommutative() {
        assertEquals(App.add(12, 30), App.add(30, 12));
    }

    @Test void testAddOverflowWrapsAround() {
        assertEquals(Integer.MIN_VALUE, App.add(Integer.MAX_VALUE, 1));
        assertEquals(Integer.MAX_VALUE, App.add(Integer.MIN_VALUE, -1));
    }

    // ---------- isPrime ----------

    @Test void testIsPrimeBelowTwo() {
        assertFalse(App.isPrime(1));
        assertFalse(App.isPrime(0));
        assertFalse(App.isPrime(-7));
        assertFalse(App.isPrime(Integer.MIN_VALUE));
    }

    @Test void testIsPrimeTwoAndThree() {
        assertTrue(App.isPrime(2));
        assertTrue(App.isPrime(3));
    }

    @Test void testIsPrimeEvenNumbers() {
        assertFalse(App.isPrime(4));
        assertFalse(App.isPrime(100));
    }

    @Test void testIsPrimeSquareOfPrime() {
        assertFalse(App.isPrime(9));
        assertFalse(App.isPrime(25));
        assertFalse(App.isPrime(49));
    }

    @Test void testIsPrimeOddComposite() {
        assertFalse(App.isPrime(15));
        assertFalse(App.isPrime(91));
    }

    @Test void testIsPrimeLargerPrimes() {
        assertTrue(App.isPrime(97));
        assertTrue(App.isPrime(7919));
        assertTrue(App.isPrime(Integer.MAX_VALUE));
    }

    // ---------- reverse ----------

    @Test void testReverseBasic() {
        assertEquals("olleh", App.reverse("hello"));
    }

    @Test void testReverseEmptyString() {
        assertEquals("", App.reverse(""));
    }

    @Test void testReverseSingleChar() {
        assertEquals("a", App.reverse("a"));
    }

    @Test void testReverseKeepsSpacesAndSymbols() {
        assertEquals("!c b a", App.reverse("a b c!"));
        assertEquals("321", App.reverse("123"));
    }

    @Test void testReverseTwiceGivesOriginal() {
        String s = "Unit Testing";
        assertEquals(s, App.reverse(App.reverse(s)));
    }

    @Test void testReverseReturnsNewString() {
        String s = "abc";
        assertNotSame(s, App.reverse(s));
    }

    @Test void testReverseNullThrows() {
        assertThrows(NullPointerException.class, () -> App.reverse(null));
    }

    // ---------- factorial ----------

    @Test void testFactorialZeroAndOne() {
        assertEquals(1, App.factorial(0));
        assertEquals(1, App.factorial(1));
    }

    @Test void testFactorialSmallNumbers() {
        assertEquals(2, App.factorial(2));
        assertEquals(6, App.factorial(3));
        assertEquals(120, App.factorial(5));
        assertEquals(3628800, App.factorial(10));
    }

    @Test void testFactorialLargestThatFitsInInt() {
        assertEquals(479001600, App.factorial(12));
    }

    @Test void testFactorialOverflowsAfterTwelve() {
        assertNotEquals(6227020800L, (long) App.factorial(13));
        assertEquals((int) 6227020800L, App.factorial(13));
    }

    @Test void testFactorialNegativeThrows() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> App.factorial(-1));
        assertEquals("Negative number", ex.getMessage());
        assertThrows(IllegalArgumentException.class, () -> App.factorial(Integer.MIN_VALUE));
    }

    // ---------- isPalindrome ----------

    @Test void testIsPalindromeSimple() {
        assertTrue(App.isPalindrome("racecar"));
        assertTrue(App.isPalindrome("abba"));
    }

    @Test void testIsPalindromeFalse() {
        assertFalse(App.isPalindrome("hello"));
        assertFalse(App.isPalindrome("ab"));
    }

    @Test void testIsPalindromeIgnoresCase() {
        assertTrue(App.isPalindrome("RaceCar"));
    }

    @Test void testIsPalindromeIgnoresSpacesAndPunctuation() {
        assertTrue(App.isPalindrome("A man, a plan, a canal: Panama"));
        assertTrue(App.isPalindrome("No 'x' in Nixon"));
    }

    @Test void testIsPalindromeWithDigits() {
        assertTrue(App.isPalindrome("12321"));
        assertFalse(App.isPalindrome("123"));
    }

    @Test void testIsPalindromeEmptyAndSingleChar() {
        assertTrue(App.isPalindrome(""));
        assertTrue(App.isPalindrome("x"));
    }

    @Test void testIsPalindromeOnlySymbols() {
        assertTrue(App.isPalindrome("!?., "));
    }

    @Test void testIsPalindromeNullThrows() {
        assertThrows(NullPointerException.class, () -> App.isPalindrome(null));
    }
@Test void testFibonacciUpToTen() {
        assertEquals(List.of(0, 1, 1, 2, 3, 5, 8), App.fibonacciUpTo(10));
    }
    @Test void testFibonacciUpToZero() {
        assertEquals(List.of(0), App.fibonacciUpTo(0));
    }
    @Test void testFibonacciUpToOne() {
        assertEquals(List.of(0, 1, 1), App.fibonacciUpTo(1));
    }
    @Test void testFibonacciLimitIsInclusive() {
        List<Integer> result = App.fibonacciUpTo(13);
        assertEquals(13, result.get(result.size() - 1));
    }
    @Test void testFibonacciNegativeThrows() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> App.fibonacciUpTo(-1));
        assertEquals("Negative input", ex.getMessage());
    }

    @Test void testCharFrequencyBasic() {
        Map<Character, Integer> freq = App.charFrequency("aab");
        assertEquals(2, freq.size());
        assertEquals(2, freq.get('a'));
        assertEquals(1, freq.get('b'));
    }
    @Test void testCharFrequencyEmptyString() {
        assertTrue(App.charFrequency("").isEmpty());
    }
    @Test void testCharFrequencyIsCaseSensitive() {
        Map<Character, Integer> freq = App.charFrequency("aA");
        assertEquals(1, freq.get('a'));
        assertEquals(1, freq.get('A'));
    }
    @Test void testCharFrequencyCountsSpacesAndSymbols() {
        Map<Character, Integer> freq = App.charFrequency("a a!");
        assertEquals(1, freq.get(' '));
        assertEquals(1, freq.get('!'));
        assertNull(freq.get('z'));
    }
    @Test void testCharFrequencyNullThrows() {
        assertThrows(NullPointerException.class, () -> App.charFrequency(null));
    }

    @Test void testIsAnagramTrue() {
        assertTrue(App.isAnagram("listen", "silent"));
    }
    @Test void testIsAnagramIgnoresCase() {
        assertTrue(App.isAnagram("Listen", "SILENT"));
    }
    @Test void testIsAnagramIgnoresSpaces() {
        assertTrue(App.isAnagram("dormitory", "dirty room"));
    }
    @Test void testIsAnagramFalse() {
        assertFalse(App.isAnagram("hello", "world"));
        assertFalse(App.isAnagram("abc", "abcd"));
        assertFalse(App.isAnagram("aab", "abb"));
    }
    @Test void testIsAnagramEmptyStrings() {
        assertTrue(App.isAnagram("", ""));
        assertTrue(App.isAnagram(" ", ""));
    }

    @Test void testAverageBasic() {
        assertEquals(2.5, App.average(new int[]{1, 2, 3, 4}), 0.0001);
    }
    @Test void testAverageSingleElement() {
        assertEquals(7.0, App.average(new int[]{7}), 0.0001);
    }
    @Test void testAverageNegatives() {
        assertEquals(-2.0, App.average(new int[]{-1, -2, -3}), 0.0001);
        assertEquals(0.0, App.average(new int[]{-5, 5}), 0.0001);
    }
    @Test void testAverageLargeValuesNoOverflow() {
        assertEquals(Integer.MAX_VALUE, App.average(new int[]{Integer.MAX_VALUE, Integer.MAX_VALUE}), 0.0001);
    }
    @Test void testAverageEmptyThrows() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> App.average(new int[]{}));
        assertEquals("Empty array", ex.getMessage());
    }

    @Test void testFilterEvensMixed() {
        assertEquals(List.of(2, 4), App.filterEvens(List.of(1, 2, 3, 4, 5)));
    }
    @Test void testFilterEvensEmptyList() {
        assertTrue(App.filterEvens(List.of()).isEmpty());
    }
    @Test void testFilterEvensNoEvens() {
        assertTrue(App.filterEvens(List.of(1, 3, 5)).isEmpty());
    }
    @Test void testFilterEvensZeroAndNegatives() {
        assertEquals(List.of(0, -2, -4), App.filterEvens(List.of(0, -1, -2, -3, -4)));
    }
    @Test void testFilterEvensKeepsOrderAndDuplicates() {
        assertIterableEquals(List.of(6, 2, 6), App.filterEvens(List.of(6, 1, 2, 6)));
    }

    @Test void testMostCommonWordBasic() {
        assertEquals("apple", App.mostCommonWord("apple banana apple cherry"));
    }
    @Test void testMostCommonWordIgnoresCase() {
        assertEquals("the", App.mostCommonWord("The cat and THE dog and the bird"));
    }
    @Test void testMostCommonWordIgnoresPunctuation() {
        assertEquals("hi", App.mostCommonWord("hi, there! hi."));
    }
    @Test void testMostCommonWordSingleWord() {
        assertEquals("hello", App.mostCommonWord("hello"));
    }
    @Test void testMostCommonWordEmptyText() {
        assertEquals("", App.mostCommonWord(""));
    }
}
