/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // ---------- add ----------

    @Test void testAdd() {
        assertEquals(5, App.add(2, 3));
        assertEquals(-1, App.add(-2, 1));
    }

    @Test void testAddWithZero() {
        assertEquals(0, App.add(0, 0));
        assertEquals(7, App.add(7, 0));
        assertEquals(7, App.add(0, 7));
    }

    @Test void testAddNegatives() {
        assertEquals(-8, App.add(-3, -5));
        assertEquals(0, App.add(-4, 4));
    }

    @Test void testAddIsCommutative() {
        assertEquals(App.add(12, 30), App.add(30, 12));
    }

    @Test void testAddOverflowWrapsAround() {
        assertEquals(Integer.MIN_VALUE, App.add(Integer.MAX_VALUE, 1));
        assertEquals(Integer.MAX_VALUE, App.add(Integer.MIN_VALUE, -1));
    }

    // ---------- isPrime ----------

    @Test void testIsPrimeBelowTwo() {
        assertFalse(App.isPrime(1));
        assertFalse(App.isPrime(0));
        assertFalse(App.isPrime(-7));
        assertFalse(App.isPrime(Integer.MIN_VALUE));
    }

    @Test void testIsPrimeTwoAndThree() {
        assertTrue(App.isPrime(2));
        assertTrue(App.isPrime(3));
    }

    @Test void testIsPrimeEvenNumbers() {
        assertFalse(App.isPrime(4));
        assertFalse(App.isPrime(100));
    }

    @Test void testIsPrimeSquareOfPrime() {
        assertFalse(App.isPrime(9));
        assertFalse(App.isPrime(25));
        assertFalse(App.isPrime(49));
    }

    @Test void testIsPrimeOddComposite() {
        assertFalse(App.isPrime(15));
        assertFalse(App.isPrime(91));
    }

    @Test void testIsPrimeLargerPrimes() {
        assertTrue(App.isPrime(97));
        assertTrue(App.isPrime(7919));
        assertTrue(App.isPrime(Integer.MAX_VALUE));
    }

    // ---------- reverse ----------

    @Test void testReverseBasic() {
        assertEquals("olleh", App.reverse("hello"));
    }

    @Test void testReverseEmptyString() {
        assertEquals("", App.reverse(""));
    }

    @Test void testReverseSingleChar() {
        assertEquals("a", App.reverse("a"));
    }

    @Test void testReverseKeepsSpacesAndSymbols() {
        assertEquals("!c b a", App.reverse("a b c!"));
        assertEquals("321", App.reverse("123"));
    }

    @Test void testReverseTwiceGivesOriginal() {
        String s = "Unit Testing";
        assertEquals(s, App.reverse(App.reverse(s)));
    }

    @Test void testReverseReturnsNewString() {
        String s = "abc";
        assertNotSame(s, App.reverse(s));
    }

    @Test void testReverseNullThrows() {
        assertThrows(NullPointerException.class, () -> App.reverse(null));
    }

    // ---------- factorial ----------

    @Test void testFactorialZeroAndOne() {
        assertEquals(1, App.factorial(0));
        assertEquals(1, App.factorial(1));
    }

    @Test void testFactorialSmallNumbers() {
        assertEquals(2, App.factorial(2));
        assertEquals(6, App.factorial(3));
        assertEquals(120, App.factorial(5));
        assertEquals(3628800, App.factorial(10));
    }

    @Test void testFactorialLargestThatFitsInInt() {
        assertEquals(479001600, App.factorial(12));
    }

    @Test void testFactorialOverflowsAfterTwelve() {
        assertNotEquals(6227020800L, (long) App.factorial(13));
        assertEquals((int) 6227020800L, App.factorial(13));
    }

    @Test void testFactorialNegativeThrows() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> App.factorial(-1));
        assertEquals("Negative number", ex.getMessage());
        assertThrows(IllegalArgumentException.class, () -> App.factorial(Integer.MIN_VALUE));
    }
}
